/**
 * Encrypts the Firebase API key and writes environment.prod.ts.
 *
 * Usage:
 *   1. Copy .env.example to .env and fill in the values.
 *   2. Run: node scripts/encrypt-key.mjs
 *
 * The script reads FIREBASE_API_KEY and ENCRYPTION_PASSPHRASE from .env,
 * AES-encrypts the key, and writes src/environments/environment.prod.ts.
 * Neither .env nor environment.prod.ts should ever be committed to git.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { createRequire } from 'module';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(__dirname, '..');

// ── Load .env ──────────────────────────────────────────────────────────────
const envPath = resolve(rootDir, '.env');
if (!existsSync(envPath)) {
  console.error('ERROR: .env file not found. Copy .env.example to .env and fill in the values.');
  process.exit(1);
}

const envVars = {};
readFileSync(envPath, 'utf8')
  .split('\n')
  .forEach(line => {
    const [key, ...rest] = line.split('=');
    if (key && rest.length) envVars[key.trim()] = rest.join('=').trim();
  });

const firebaseApiKey = envVars['FIREBASE_API_KEY'];
const passphrase = envVars['ENCRYPTION_PASSPHRASE'];

if (!firebaseApiKey || !passphrase) {
  console.error('ERROR: FIREBASE_API_KEY and ENCRYPTION_PASSPHRASE must be set in .env');
  process.exit(1);
}

// ── Encrypt ─────────────────────────────────────────────────────────────────
const require = createRequire(import.meta.url);
const CryptoJS = require('crypto-js');

const encryptedKey = CryptoJS.AES.encrypt(firebaseApiKey, passphrase).toString();

// ── Write environment.prod.ts ────────────────────────────────────────────────
const output = `// Auto-generated by scripts/encrypt-key.mjs — DO NOT commit this file.
export const environment = {
  production: true,
  firebaseApiKey: '${encryptedKey}',
  encryptionPassphrase: '${passphrase}',
  firebaseSignUpUrl: 'https://identitytoolkit.googleapis.com/v1/accounts:signUp',
  firebaseSignInUrl: 'https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword',
};
`;

const outPath = resolve(rootDir, 'src/environments/environment.prod.ts');
writeFileSync(outPath, output, 'utf8');

console.log('environment.prod.ts generated successfully.');
console.log(`  Encrypted key (preview): ${encryptedKey.slice(0, 20)}...`);
